// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_spotify_user_by_spotify_id.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const getSpotifyUserBySpotifyId = `-- name: GetSpotifyUserBySpotifyId :one

SELECT
    spotify_id,
    display_name,
    last_scan,
    created_at
FROM
    spotify.users su
WHERE
    su.spotify_id = $1
`

type GetSpotifyUserBySpotifyIdRow struct {
	SpotifyID   string
	DisplayName sql.NullString
	LastScan    sql.NullTime
	CreatedAt   time.Time
}

func (q *Queries) GetSpotifyUserBySpotifyId(ctx context.Context, spotifyID string) (GetSpotifyUserBySpotifyIdRow, error) {
	row := q.db.QueryRowContext(ctx, getSpotifyUserBySpotifyId, spotifyID)
	var i GetSpotifyUserBySpotifyIdRow
	err := row.Scan(
		&i.SpotifyID,
		&i.DisplayName,
		&i.LastScan,
		&i.CreatedAt,
	)
	return i, err
}
