// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_user_by_sub.sql

package database

import (
	"context"
	"database/sql"
)

const getUserBySub = `-- name: GetUserBySub :one

SELECT 
    id,
    google_sub,
    email,
    picture_url,
    full_name,
    given_name,
    family_name,
    created_at,
    updated_at
FROM 
    app.users u
WHERE
    u.google_sub = $1
`

func (q *Queries) GetUserBySub(ctx context.Context, googleSub sql.NullString) (AppUser, error) {
	row := q.db.QueryRowContext(ctx, getUserBySub, googleSub)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.GoogleSub,
		&i.Email,
		&i.PictureUrl,
		&i.FullName,
		&i.GivenName,
		&i.FamilyName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
