// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type SpotifyItemType string

const (
	SpotifyItemTypeTrack   SpotifyItemType = "track"
	SpotifyItemTypeEpisode SpotifyItemType = "episode"
)

func (e *SpotifyItemType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SpotifyItemType(s)
	case string:
		*e = SpotifyItemType(s)
	default:
		return fmt.Errorf("unsupported scan type for SpotifyItemType: %T", src)
	}
	return nil
}

type NullSpotifyItemType struct {
	SpotifyItemType SpotifyItemType
	Valid           bool // Valid is true if SpotifyItemType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSpotifyItemType) Scan(value interface{}) error {
	if value == nil {
		ns.SpotifyItemType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SpotifyItemType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSpotifyItemType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SpotifyItemType), nil
}

type AppUser struct {
	ID         int64
	GoogleSub  sql.NullString
	Email      sql.NullString
	PictureUrl interface{}
	FullName   sql.NullString
	GivenName  sql.NullString
	FamilyName sql.NullString
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type SpotifyEpisode struct {
	EpisodeID         string
	IsExplicit        bool
	Description       sql.NullString
	DurationMs        int32
	Languages         []string
	Name              string
	ReleaseDate       time.Time
	RestrictionReason sql.NullString
	Show              string
}

type SpotifyPlaylist struct {
	Owner       string
	PlaylistID  string
	Name        string
	Description sql.NullString
	Created     time.Time
	IsDeleted   sql.NullBool
}

type SpotifyPlaylistItem struct {
	PlaylistID    sql.NullString
	TrackID       sql.NullString
	ItemType      SpotifyItemType
	AddedAt       time.Time
	AddedBy       string
	IsLocal       bool
	IsUnavailable bool
	IsDeleted     bool
	EpisodeID     sql.NullString
}

type SpotifyTrack struct {
	TrackID          string
	AlbumID          string
	AlbumName        string
	Artists          []string
	AvailableMarkets []string
	IsExplicit       sql.NullBool
	// https://en.wikipedia.org/wiki/International_Standard_Recording_Code
	Isrc sql.NullString
	// https://en.wikipedia.org/wiki/International_Article_Number
	Ian sql.NullString
	// https://en.wikipedia.org/wiki/Universal_Product_Code
	Upc               sql.NullString
	RestrictionReason sql.NullString
	Name              string
	IsLocal           sql.NullBool
}

type SpotifyUser struct {
	SpotifyID   string
	DisplayName sql.NullString
	InternalID  int64
	LastScan    sql.NullTime
	Created     time.Time
}
