// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: upsert_spotify_user.sql

package database

import (
	"context"
	"database/sql"
)

const upsertSpotifyUser = `-- name: UpsertSpotifyUser :one

INSERT INTO spotify.users (
        spotify_id,
        display_name,
        created_at,
        updated_at
    )
VALUES (
    $1,
    $2,
    NOW(),
    NOW()
) ON CONFLICT (spotify_id) DO
UPDATE
SET display_name = $2,
    updated_at = NOW()
RETURNING spotify_id, display_name, last_scan, created_at, updated_at
`

type UpsertSpotifyUserParams struct {
	SpotifyID   string
	DisplayName sql.NullString
}

func (q *Queries) UpsertSpotifyUser(ctx context.Context, arg UpsertSpotifyUserParams) (SpotifyUser, error) {
	row := q.db.QueryRowContext(ctx, upsertSpotifyUser, arg.SpotifyID, arg.DisplayName)
	var i SpotifyUser
	err := row.Scan(
		&i.SpotifyID,
		&i.DisplayName,
		&i.LastScan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
